### ISSUE TITLE
ACK isn't requested during CCTXD in goby-chat when device IDs are 0 and 1

### ISSUE THREAD

**Issue by jamesoncollins** [GobySoft/goby3-examples#9]
In the goby-chat example if I set the src and dest IDs to 0 and 1 I will only receive ack's in one direction.  If I set it to 10 and 11, I will get acks in both directions.  It seems in the former case the ACK flag isnt set when the source is 1 and the dest is 0.

Here are some log examples.

Working (side A log):
{goby::acomms::modemdriver::out::1}: D: $CCTXD,11,10,1,046a1dd095cdd181888501000000000000000000000000000000000000000000*71

Working (side B log):
{goby::acomms::modemdriver::out::1}: D: $CCTXD,10,11,1,044b1dd095cdd181848901000000000000000000000000000000000000000000*70

Not working (side A log):
{goby::acomms::modemdriver::out::1}: D: $CCTXD,0,1,1,04011cd095cdd181848901000000000000000000000000000000000000000000*20

Not working (side B log):
{goby::acomms::modemdriver::out::1}: D: $CCTXD,1,0,0,04201cd095cdd181888501000000000000000000000000000000000000000000*22

**Comment by jamesoncollins** [comment]
This might be by design.  I see now that BROADCAST_ID is 0.

**Comment by tsaubergine** [comment]
This is by design, don't assign 0 (this is broadcast)
